function openModal(title,sub,html){modalTitle.textContent=title;modalSub.textContent=sub||'';modalBody.innerHTML=html;modal.hidden=false;backdrop.hidden=false;document.body.style.overflow='hidden'}
function closeModal(){modal.hidden=true;backdrop.hidden=true;document.body.style.overflow=''}
function openChinese(e){openModal(tr('showChinese'),state.lang==='zh'?e.name.th:loc(e.name),`<div class="driver-cn">${esc(e.cn)}</div>${e.route?`<div class="notice">${esc(loc(e.route))}</div>`:''}<div class="actions"><button class="btn primary" data-copy="${encodeURIComponent(e.cn)}">${tr('copyChinese')}</button><button class="btn" data-speak="${encodeURIComponent(e.cn)}">${tr('speak')}</button><a class="btn" href="${amapUrl(e)}" target="_blank">${tr('openAmap')}</a></div>`)}
function openDriver(){const h=DATA.trip.hotel;openModal(tr('driverTitle'),tr('driverHint'),`<div class="driver-cn">${esc(h.cn)}</div><div class="driver-address">${esc(h.address)}</div><div class="actions"><button class="btn primary" data-copy="${encodeURIComponent(h.cn)}">${tr('copyChinese')}</button><button class="btn" data-copy="${encodeURIComponent(h.address)}">${tr('address')}</button><button class="btn" data-speak="${encodeURIComponent('请送我们去这个酒店，谢谢。')}">${tr('speak')}</button><a class="btn" href="${amapUrl({cn:h.cn,city:'上海'})}" target="_blank">${tr('openAmap')}</a></div>`)}
function openEmergency(){const t=DATA.trip;openModal(tr('sos'),`110 · 119 · 120`, `<div class="sos-grid">${t.emergency.map(x=>`<a class="sos" href="tel:${esc(x.number)}"><b>${esc(loc(x.label))}</b><strong>${esc(x.number)}</strong></a>`).join('')}</div><div class="card"><h3>🏨 ${tr('backHotel')}</h3><div class="driver-cn" style="font-size:28px">${esc(t.hotel.cn)}</div><div class="driver-address">${esc(t.hotel.address)}</div><div class="actions"><button class="btn primary" data-driver="hotel">${tr('driverTitle')}</button><a class="btn" href="tel:${esc(t.hotel.phone.replace(/[^+\d]/g,''))}">${tr('call')}</a></div></div><div class="card"><h3>✚ ${tr('insurance')}</h3><a class="btn" href="tel:${esc(t.insurance.overseas.replace(/\s/g,''))}">${esc(t.insurance.overseas)}</a></div>`)}
function guideHtml(key){const g=DATA.guides?.[key];if(!g)return '';return `<div class="card"><h3>${esc(loc(g.title))}</h3><ol class="arrival-list">${g.steps.map(x=>`<li>${esc(loc(x))}</li>`).join('')}</ol></div>`}
function showGuide(key){const g=DATA.guides?.[key];if(!g)return;openModal(loc(g.title),'',guideHtml(key))}
function openHelp(){const lost=DATA.phrases[0],toilet=DATA.phrases[2];openModal(tr('help'),tr('nextStep'),`<div class="more-grid"><button class="more-btn" data-help-action="lost"><b>${tr('helpLost')}</b><small>${esc(lost.zh)}</small></button><button class="more-btn" data-help-action="hotel"><b>${tr('helpHotel')}</b><small>${esc(DATA.trip.hotel.cn)}</small></button><button class="more-btn" data-help-action="didi"><b>${tr('helpDidi')}</b><small>目的地 · 上车点 · 车牌号</small></button><button class="more-btn" data-help-action="metro"><b>${tr('helpMetro')}</b><small>地铁 · 换乘 · 出口</small></button><button class="more-btn" data-help-action="train"><b>${tr('helpTrain')}</b><small>车次 · 检票口 · 车厢</small></button><button class="more-btn" data-help-action="alipay"><b>${tr('helpAlipay')}</b><small>扫一扫 · 付款</small></button><button class="more-btn" data-help-action="food"><b>${tr('helpFood')}</b><small>不要辣 · 买单</small></button><button class="more-btn" data-help-action="toilet"><b>${tr('helpToilet')}</b><small>${esc(toilet.zh)}</small></button></div>`)}
function showPhrase(p){openModal(tr('help'),state.lang==='zh'?p.zh:p.th,`<div class="driver-cn">${esc(p.zh)}</div><div class="actions"><button class="btn primary" data-copy="${encodeURIComponent(p.zh)}">${tr('copyChinese')}</button><button class="btn" data-speak="${encodeURIComponent(p.zh)}">${tr('speak')}</button></div>`)}

function exportData(){const data={version:3,exportedAt:new Date().toISOString(),checklist:getChecklistState(),expenses:getExpenses(),done:[...getSet('sh-done')],favorites:[...getSet('sh-favorites')],privateMembers:loadJSON('sh-private-members',[]),settings:{language:state.lang,fontSize:state.fontSize,family:state.family}};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='shanghai-trip-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function importData(file){if(!file)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(d.checklist)saveJSON('sh-checklist',d.checklist);if(d.expenses)saveExpenses(d.expenses);if(d.done)saveJSON('sh-done',d.done);if(d.favorites)saveJSON('sh-favorites',d.favorites);if(d.privateMembers)saveJSON('sh-private-members',d.privateMembers);if(d.settings?.language)localStorage.setItem('sh-ui-language',d.settings.language);toast(tr('importOk'));render()}catch{alert(tr('invalidFile'))}};r.readAsText(file)}
