(function(){
'use strict';

var frame=document.getElementById('legacy');
var header=document.querySelector('.header');
var sheetGrid=document.getElementById('sheetGrid');
var sheetTitle=document.getElementById('sheetTitle');
var readiness=null;

var css=document.createElement('style');
css.textContent=`
.pr-status-btn{margin-left:auto;min-height:36px;border:1px solid #efc7d7;border-radius:999px;background:#fff;color:#7e3150;padding:6px 10px;font:800 10px/1.2 inherit;white-space:nowrap}.pr-status-btn.offline{background:#fff0d9;color:#744b11;border-color:#edd3a5}.header .emergency{margin-left:3px}
.pr-backdrop{position:fixed;inset:0;z-index:90;background:rgba(43,15,28,.53);opacity:0;pointer-events:none;transition:.18s}.pr-modal{position:fixed;z-index:91;left:10px;right:10px;bottom:calc(10px + env(safe-area-inset-bottom));max-width:600px;max-height:min(78dvh,720px);margin:auto;overflow:auto;background:#fff;border:1px solid #efc9d8;border-radius:26px;box-shadow:0 28px 80px rgba(62,17,37,.34);transform:translateY(24px);opacity:0;pointer-events:none;transition:.18s}.pr-modal.open,.pr-backdrop.open{opacity:1;pointer-events:auto}.pr-modal.open{transform:none}.pr-modal-head{position:sticky;top:0;z-index:2;display:flex;justify-content:space-between;align-items:start;gap:12px;padding:16px;background:rgba(255,255,255,.97);border-bottom:1px solid #f0d5e0}.pr-modal-head h2{font-size:20px;margin:0}.pr-modal-head p{font-size:12px;color:#78636c;margin:3px 0 0}.pr-close{width:42px;height:42px;flex:none;border:0;border-radius:50%;background:#fff0f6;color:#9b3159;font-size:24px}.pr-body{padding:14px 14px 20px}.pr-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.pr-call,.pr-card,.pr-check-row{border:1px solid #f0d5e0;border-radius:17px;background:#fff;padding:12px}.pr-call{text-decoration:none;color:#36212b;display:block}.pr-call b,.pr-call strong{display:block}.pr-call strong{font-size:24px;color:#b92862;margin-top:3px}.pr-call small,.pr-card small,.pr-check-row small{color:#78636c}.pr-card{margin-top:9px}.pr-card h3{margin:0 0 7px}.pr-driver-cn{font-size:clamp(28px,8vw,44px);line-height:1.3;font-weight:900;text-align:center;margin:13px 0;color:#2d1720;word-break:break-word}.pr-driver-address{font-size:20px;line-height:1.45;text-align:center;background:#fff0f6;border-radius:16px;padding:13px;margin:10px 0}.pr-actions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-top:10px}.pr-actions button,.pr-actions a{min-height:46px;border:1px solid #eac3d2;border-radius:14px;background:#fff;color:#943656;text-decoration:none;display:flex;align-items:center;justify-content:center;padding:8px;font:800 13px/1.2 inherit}.pr-actions .primary{background:#e84887;color:#fff;border-color:#e84887}.pr-check-row{margin:8px 0}.pr-check-row header{display:flex;align-items:center;justify-content:space-between;gap:8px}.pr-badge{display:inline-flex;align-items:center;border-radius:999px;padding:4px 8px;font-size:10px;font-weight:900;background:#e7f6ec;color:#276944}.pr-badge.live{background:#fff0db;color:#86550d}.pr-badge.pending{background:#fff0e8;color:#92452d}.pr-badge.important{background:#fde9ed;color:#9b2949}.pr-badge.ticket{background:#edf1ff;color:#465796}.pr-source{color:#a1325c;text-decoration:none;font-size:11px;font-weight:800}.pr-net{display:flex;align-items:center;gap:6px;padding:8px 10px;border-radius:13px;background:#f8f4f6;margin-bottom:9px;font-size:12px}.pr-net i{width:8px;height:8px;border-radius:50%;background:#349866}.pr-net.offline i{background:#d99022}
.pr-energy{margin:10px 0 14px;padding:13px;border:1px solid #efcbd9;border-radius:18px;background:linear-gradient(145deg,#fff,#fff5f9)}.pr-energy h3{margin:0;font-size:17px}.pr-energy p{margin:4px 0 9px;color:#715664;font-size:12px}.pr-energy .pr-actions{grid-template-columns:repeat(3,minmax(0,1fr))}.pr-energy .pr-actions button{font-size:11px;padding:7px 4px}.pr-energy-choice{margin-top:8px;padding:9px;border-radius:12px;background:#fff;color:#694255;font-size:12px}
@media(max-width:520px){.brand small{font-size:9px}.brand b{font-size:16px}.pr-status-btn{padding-inline:8px}.pr-grid{grid-template-columns:1fr 1fr}.pr-actions{grid-template-columns:1fr 1fr}}
@media(max-width:390px){.pr-status-btn{font-size:0;width:38px;padding:0}.pr-status-btn:before{content:'✓';font-size:15px}.brand small{letter-spacing:.06em}.pr-energy .pr-actions{grid-template-columns:1fr}}
`;
document.head.appendChild(css);

var statusBtn=document.createElement('button');
statusBtn.className='pr-status-btn';
statusBtn.type='button';
statusBtn.textContent='✓ พร้อมใช้';
statusBtn.setAttribute('aria-label','สถานะความพร้อมของข้อมูลทริป');
header.insertBefore(statusBtn,document.getElementById('emergencyBtn'));

var backdrop=document.createElement('div');
backdrop.className='pr-backdrop';
var modal=document.createElement('section');
modal.className='pr-modal';
modal.setAttribute('role','dialog');
modal.setAttribute('aria-modal','true');
modal.innerHTML='<div class="pr-modal-head"><div><h2 id="prTitle">ข้อมูลสำคัญ</h2><p id="prSubtitle"></p></div><button class="pr-close" type="button" aria-label="ปิด">×</button></div><div class="pr-body" id="prBody"></div>';
document.body.appendChild(backdrop);document.body.appendChild(modal);
var prTitle=modal.querySelector('#prTitle'),prSubtitle=modal.querySelector('#prSubtitle'),prBody=modal.querySelector('#prBody');

function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function closeModal(){modal.classList.remove('open');backdrop.classList.remove('open')}
function openModal(title,subtitle,html){prTitle.textContent=title;prSubtitle.textContent=subtitle||'';prBody.innerHTML=html;modal.classList.add('open');backdrop.classList.add('open');setTimeout(function(){modal.querySelector('.pr-close').focus()},20)}
function copy(value){if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(value).catch(function(){})}}
function badgeClass(s){return s==='live'?'live':s==='pending'?'pending':s==='important'?'important':s==='ticket'?'ticket':''}
function fallbackData(){return {last_verified:'2026-08-26',checks:[],emergency:{police:'110',fire:'119',ambulance:'120',traffic:'122',shanghai_government:'12345'},hotel:{name:'Yitel Collection (Shanghai Train Station)',cn:'和颐至尚酒店(上海火车站南广场店)',address_cn:'上海市静安区天目西路511号',phone:'+86-21-52711555-0'},insurance:{provider:'MSIG',overseas_assistance:'+66 2 039 5704',customer_service:'+66 2 825 8888'},photo_policy:{ambient_matches:[],ambient_label:'ภาพบรรยากาศย่าน/กิจกรรม'}}}

function updateNetwork(){var online=navigator.onLine;statusBtn.classList.toggle('offline',!online);statusBtn.textContent=online?'✓ พร้อมใช้':'Offline ✓';statusBtn.title=online?'ออนไลน์ — ข้อมูลหลักพร้อมใช้':'ออฟไลน์ — ข้อมูลหลักในเครื่องยังใช้ได้ แผนที่/ข้อมูลสดอาจไม่โหลด'}
window.addEventListener('online',updateNetwork);window.addEventListener('offline',updateNetwork);updateNetwork();

function emergencyHtml(){var d=readiness||fallbackData(),e=d.emergency||{},h=d.hotel||{},i=d.insurance||{};return '<div class="pr-net '+(navigator.onLine?'':'offline')+'"><i></i><b>'+(navigator.onLine?'ออนไลน์':'ออฟไลน์')+'</b><span> · เบอร์และที่อยู่ด้านล่างใช้ได้โดยไม่ต้องเปิดแผนที่</span></div><div class="pr-grid">'+
'<a class="pr-call" href="tel:'+esc(e.police||'110')+'"><b>ตำรวจ · 报警</b><strong>'+esc(e.police||'110')+'</strong><small>Police</small></a>'+
'<a class="pr-call" href="tel:'+esc(e.ambulance||'120')+'"><b>รถพยาบาล · 急救</b><strong>'+esc(e.ambulance||'120')+'</strong><small>Ambulance</small></a>'+
'<a class="pr-call" href="tel:'+esc(e.fire||'119')+'"><b>ดับเพลิง · 火警</b><strong>'+esc(e.fire||'119')+'</strong><small>Fire</small></a>'+
'<a class="pr-call" href="tel:'+esc(e.traffic||'122')+'"><b>อุบัติเหตุจราจร</b><strong>'+esc(e.traffic||'122')+'</strong><small>Traffic police</small></a></div>'+
'<div class="pr-card"><h3>✚ '+esc(i.provider||'Travel insurance')+'</h3><div class="pr-grid"><a class="pr-call" href="tel:'+esc((i.overseas_assistance||'').replace(/\s/g,''))+'"><b>ช่วยเหลือต่างประเทศ</b><strong style="font-size:18px">'+esc(i.overseas_assistance||'')+'</strong></a><a class="pr-call" href="tel:'+esc((i.customer_service||'').replace(/\s/g,''))+'"><b>บริการลูกค้า</b><strong style="font-size:18px">'+esc(i.customer_service||'')+'</strong></a></div></div>'+
'<div class="pr-card"><h3>🏨 กลับโรงแรม</h3><b>'+esc(h.name||'')+'</b><div class="pr-driver-cn">'+esc(h.cn||'')+'</div><div class="pr-driver-address">'+esc(h.address_cn||'')+'</div><div class="pr-actions"><button class="primary" data-pr-copy="'+esc(h.cn||'')+'">Copy ชื่อจีน</button><button data-pr-driver-hotel>ให้คนขับดูเต็มจอ</button><a href="tel:'+esc((h.phone||'').replace(/[^+\d]/g,''))+'">โทรโรงแรม</a><button data-pr-copy="'+esc(h.address_cn||'')+'">Copy ที่อยู่จีน</button></div></div>';
}
function openEmergency(){openModal('ฉุกเฉิน · Emergency','110 / 119 / 120 · โรงแรม · ประกัน',emergencyHtml())}

function driverHtml(cn,address,label){return '<div class="pr-card"><small>请送我们去这里，谢谢</small><div class="pr-driver-cn">'+esc(cn)+'</div>'+(address?'<div class="pr-driver-address">'+esc(address)+'</div>':'')+(label?'<p style="text-align:center">'+esc(label)+'</p>':'')+'<div class="pr-actions"><button class="primary" data-pr-copy="'+esc(cn)+'">Copy 中文</button>'+(address?'<button data-pr-copy="'+esc(address)+'">Copy 地址</button>':'')+'</div></div><p style="text-align:center;color:#78636c;font-size:12px">ยื่นหน้าจอนี้ให้คนขับรถ หรือกด Copy แล้ววางใน DiDi / AMap</p>'}
function openDriver(cn,address,label){openModal('ให้คนขับดู · 给司机看','ตัวอักษรจีนขนาดใหญ่',driverHtml(cn,address,label))}

function readinessHtml(){var d=readiness||fallbackData(),checks=d.checks||[];return '<div class="pr-net '+(navigator.onLine?'':'offline')+'"><i></i><b>'+(navigator.onLine?'ออนไลน์':'ออฟไลน์')+'</b><span> · ตรวจข้อมูลล่าสุด '+esc(d.last_verified||'')+'</span></div>'+checks.map(function(x){return '<div class="pr-check-row"><header><span class="pr-badge '+badgeClass(x.status)+'">'+esc(x.label)+'</span>'+(x.source_url?'<a class="pr-source" href="'+esc(x.source_url)+'" target="_blank" rel="noopener">แหล่งข้อมูล ↗</a>':'')+'</header><b>'+esc((x.match||[])[1]||(x.match||[])[0]||x.id)+'</b><small style="display:block;margin-top:5px">'+esc(x.detail)+'</small></div>'}).join('')+'<div class="pr-card"><b>หลักการใช้งาน</b><small style="display:block;margin-top:5px">✓ ยืนยันแล้ว = ข้อมูลค่อนข้างคงที่ · เช็กวันจริง = เวลา/บริการเปลี่ยนได้ · รอยืนยันตั๋ว = ยังไม่ควรยึดเวลาในแผนเป็นตั๋วจริง</small></div>'}
function openReadiness(){openModal('ความพร้อมของข้อมูล','แยกข้อมูลยืนยันแล้ว / ต้องเช็กสด / รอจอง',readinessHtml())}

function findCheck(txt){if(!readiness||!readiness.checks)return null;return readiness.checks.find(function(x){return (x.match||[]).some(function(k){return k&&txt.indexOf(k)>-1})})||null}
function addCheck(container,check){if(!check||container.querySelector(':scope .pr-inline-check'))return;var target=container.querySelector('.event-body,.restaurant-body,.place-body,.walk-detail-body')||container;var el=target.ownerDocument.createElement('details');el.className='pr-inline-check';el.innerHTML='<summary><span class="pr-inline-badge '+badgeClass(check.status)+'">'+esc(check.label)+'</span><small>ตรวจ '+esc(readiness.last_verified||'')+' ▾</small></summary><p>'+esc(check.detail)+'</p>'+(check.source_url?'<a href="'+esc(check.source_url)+'" target="_blank" rel="noopener">แหล่งข้อมูลทางการ ↗</a>':'');target.insertBefore(el,target.firstChild)}
function addressFrom(container){var txt=container.textContent||'';var match=txt.match(/(?:上海市|杭州市)?[^\n]{0,25}(?:路|街|弄|号)[^\n]{0,12}/);return match?match[0].trim():''}
function addDriver(container){if(container.querySelector('[data-pr-driver]'))return;var cn=container.querySelector('.cn,.cn-inline');if(!cn||!cn.textContent.trim())return;var value=cn.textContent.trim();if(value.length<2)return;var actions=container.querySelector('.actions');if(!actions)return;var b=container.ownerDocument.createElement('button');b.className='btn ghost';b.type='button';b.dataset.prDriver='1';b.textContent='🚕 ให้คนขับดู';b.addEventListener('click',function(e){e.preventDefault();e.stopPropagation();openDriver(value,addressFrom(container),(container.querySelector('h3,b')||{}).textContent||'')});actions.appendChild(b)}
function addPhotoLabel(container){if(!readiness||!readiness.photo_policy)return;if(container.querySelector('.pr-photo-label'))return;var txt=container.textContent||'';var ambient=(readiness.photo_policy.ambient_matches||[]).some(function(k){return txt.indexOf(k)>-1});if(!ambient)return;var photo=container.querySelector('.event-photo,.restaurant-cover,.place-photo');if(!photo)return;photo.style.position='relative';var s=container.ownerDocument.createElement('span');s.className='pr-photo-label';s.textContent='🖼 '+(readiness.photo_policy.ambient_label||'ภาพบรรยากาศ');photo.appendChild(s)}
function maskVisibleSensitive(d){var walker=d.createTreeWalker(d.body,NodeFilter.SHOW_TEXT);var n;while((n=walker.nextNode())){if(n.parentElement&&/^(SCRIPT|STYLE)$/.test(n.parentElement.tagName))continue;n.nodeValue=n.nodeValue.replace(/26-43239988/g,'••••••••').replace(/MZXMN8/g,'••••••')}}
function addEnergy(d){var hero=d.querySelector('.hero');if(!hero||d.querySelector('.pr-energy'))return;var txt=(hero.textContent||'')+' '+((d.querySelector('.timeline')||{}).textContent||'');if(txt.indexOf('Arrival')===-1&&txt.indexOf('嘉陵菜市场')===-1)return;var current=localStorage.getItem('sh-day1-energy')||'full';var box=d.createElement('section');box.className='pr-energy';box.innerHTML='<h3>⚡ Day 1 · ระดับพลังครอบครัว</h3><p>ลงเครื่องเช้ามาก เลือกโหมดหน้างานได้โดยไม่รู้สึกว่าต้องทำทุกจุด</p><div class="pr-actions"><button data-energy="full">เต็มแผน</button><button data-energy="short">ลดครึ่งวัน</button><button data-energy="rest">พักก่อน</button></div><div class="pr-energy-choice"></div>';hero.insertAdjacentElement('afterend',box);function paint(v){var t=v==='short'?'ลดครึ่งวัน: ตลาดสั้น ๆ → Anfu/Wukang → กลับพัก · Xintiandi เป็น optional':v==='rest'?'พักก่อน: ฝากกระเป๋า/พัก → เริ่ม Wukang หรือ Xintiandi ช่วงบ่าย · ตัด City Walk ยาว':'เต็มแผน: ทำตาม Timeline แต่ใช้ Family shortcut ทันทีเมื่อเริ่มเหนื่อย';box.querySelector('.pr-energy-choice').textContent=t;box.querySelectorAll('[data-energy]').forEach(function(b){b.style.background=b.dataset.energy===v?'#e84887':'#fff';b.style.color=b.dataset.energy===v?'#fff':'#943656'})}box.addEventListener('click',function(e){var b=e.target.closest('[data-energy]');if(!b)return;localStorage.setItem('sh-day1-energy',b.dataset.energy);paint(b.dataset.energy)});paint(current)}
function injectFrameStyles(d){if(d.getElementById('production-readiness-frame'))return;var st=d.createElement('style');st.id='production-readiness-frame';st.textContent='.pr-inline-check{margin:0 0 10px;border:1px solid #efd2dd;border-radius:12px;background:#fffafc;overflow:hidden}.pr-inline-check summary{display:flex;justify-content:space-between;align-items:center;gap:7px;padding:8px 9px;cursor:pointer;list-style:none}.pr-inline-check p{margin:0;padding:0 9px 8px;font-size:12px;color:#6e5260}.pr-inline-check a{display:inline-block;padding:0 9px 9px;color:#a8325d;font-size:11px;font-weight:800}.pr-inline-badge{display:inline-flex;border-radius:999px;padding:3px 7px;background:#e8f6ed;color:#286b45;font-size:10px;font-weight:900}.pr-inline-badge.live{background:#fff0db;color:#86550d}.pr-inline-badge.pending{background:#fff0e8;color:#92452d}.pr-inline-badge.important{background:#fde9ed;color:#9b2949}.pr-inline-badge.ticket{background:#edf1ff;color:#465796}.pr-photo-label{position:absolute;right:7px;bottom:7px;z-index:4;padding:4px 7px;border-radius:999px;background:rgba(40,24,31,.78);color:#fff;font-size:9px;font-weight:800}.pr-energy .pr-actions button{border:1px solid #e7bed0;border-radius:11px;background:#fff;color:#943656;min-height:40px;font:800 11px inherit}';d.head.appendChild(st)}
function enhanceFrame(){var d;try{d=frame.contentDocument}catch(e){return}if(!d||!d.body)return;injectFrameStyles(d);maskVisibleSensitive(d);var containers=d.querySelectorAll('.event-card,.idea-card,.restaurant-card,.place-card,.walk-detail,.travel-doc-route');containers.forEach(function(c){var check=findCheck(c.textContent||'');if(check)addCheck(c,check);addDriver(c);addPhotoLabel(c)});addEnergy(d)}
function observeFrame(){var d;try{d=frame.contentDocument}catch(e){return}if(!d)return;var app=d.getElementById('app');if(!app)return;enhanceFrame();if(app.dataset.prObserved)return;app.dataset.prObserved='1';new MutationObserver(function(){requestAnimationFrame(enhanceFrame)}).observe(app,{childList:true,subtree:true})}
function addMoreActions(){if(!sheetGrid||!sheetTitle||sheetTitle.textContent!=='เพิ่มเติม')return;if(sheetGrid.querySelector('[data-pr-action]'))return;sheetGrid.insertAdjacentHTML('beforeend','<button type="button" data-pr-action="readiness"><b>✓ ความพร้อมข้อมูล</b><small>ยืนยันแล้ว / เช็กสด / รอจอง</small></button><button type="button" data-pr-action="hotel"><b>🚕 ให้คนขับดู</b><small>ชื่อและที่อยู่โรงแรมภาษาจีน</small></button>')}

statusBtn.addEventListener('click',openReadiness);
var emergencyBtn=document.getElementById('emergencyBtn');if(emergencyBtn)emergencyBtn.addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();openEmergency()},true);
backdrop.addEventListener('click',closeModal);modal.querySelector('.pr-close').addEventListener('click',closeModal);
document.addEventListener('keydown',function(e){if(e.key==='Escape'&&modal.classList.contains('open'))closeModal()});
modal.addEventListener('click',function(e){var cp=e.target.closest('[data-pr-copy]');if(cp){copy(cp.dataset.prCopy);cp.textContent='คัดลอกแล้ว ✓';setTimeout(function(){cp.textContent='Copy'},900);return}if(e.target.closest('[data-pr-driver-hotel]')){var h=(readiness||fallbackData()).hotel||{};openDriver(h.cn,h.address_cn,h.name)}});
if(sheetGrid){sheetGrid.addEventListener('click',function(e){var b=e.target.closest('[data-pr-action]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();if(b.dataset.prAction==='readiness')openReadiness();else{var h=(readiness||fallbackData()).hotel||{};openDriver(h.cn,h.address_cn,h.name)}},true)}
document.querySelector('.nav').addEventListener('click',function(){setTimeout(addMoreActions,10)},true);
new MutationObserver(addMoreActions).observe(document.getElementById('sheet')||document.body,{childList:true,subtree:true,attributes:true});
frame.addEventListener('load',function(){setTimeout(observeFrame,60);setTimeout(observeFrame,400)});

fetch('../data/trip-readiness.json',{cache:'no-cache'}).then(function(r){if(!r.ok)throw new Error('readiness '+r.status);return r.json()}).then(function(d){readiness=d;enhanceFrame()}).catch(function(){readiness=fallbackData();statusBtn.title='ใช้ข้อมูล readiness สำรองในเครื่อง'}).finally(function(){enhanceFrame();addMoreActions()});
setTimeout(observeFrame,150);
})();
