(function(){
'use strict';
var frame=document.getElementById('legacy'),KEY='sh-journey-controller-v1';
function st(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return {}}}
function mins(s){var m=String(s||'').match(/(\d{1,2}):(\d{2})/);return m?Number(m[1])*60+Number(m[2]):9999}
function selectDay(doc,day){var chips=Array.from(doc.querySelectorAll('.day-chip,button[data-day],button[data-day-index]'));var hit=chips.find(function(b){var t=(b.textContent||'').replace(/\s+/g,' ');var di=b.dataset&&((b.dataset.dayIndex!=null?Number(b.dataset.dayIndex)+1:null)||(b.dataset.day!=null?Number(b.dataset.day)+1:null));return di===day||new RegExp('Day\\s*'+day+'\\b','i').test(t)});if(hit&&!hit.classList.contains('active'))hit.click()}
function render(){var s=st();if(!s.simulating)return;var doc;try{doc=frame.contentDocument}catch(e){return}if(!doc)return;selectDay(doc,Number(s.simDay||1));setTimeout(function(){var timeline=doc.querySelector('.timeline');if(!timeline)return;var old=doc.querySelector('.jc-simulator-card');if(old)old.remove();var cards=Array.from(timeline.querySelectorAll('.event-card')).map(function(c){return {time:(c.querySelector('.time-badge,.event-time,time')||{}).textContent||'',name:(c.querySelector('.event-head h3,h3')||{}).textContent||'',cn:(c.querySelector('.cn,.cn-inline')||{}).textContent||''}}).filter(function(x){return x.name});if(!cards.length)return;var now=mins(s.simTime||'09:00'),idx=cards.findIndex(function(x){return mins(x.time)>=now-15});if(idx<0)idx=cards.length-1;var prev=idx>0?cards[idx-1]:null,cur=cards[idx],next=idx+1<cards.length?cards[idx+1]:null;var box=doc.createElement('section');box.className='jc-simulator-card';box.innerHTML='<b>▶ SIMULATION · Day '+Number(s.simDay||1)+' · '+(s.simTime||'09:00')+'</b><div><small>ก่อนหน้า</small><strong>'+(prev?'✓ '+prev.time+' '+prev.name:'—')+'</strong></div><div class="current"><small>ตอนนี้ / ถัดไป</small><strong>'+cur.time+' '+cur.name+'</strong>'+(cur.cn?'<span>'+cur.cn+'</span>':'')+'</div><div><small>หลังจากนี้</small><strong>'+(next?next.time+' '+next.name:'จบแผนวันนี้')+'</strong></div><small>นี่เป็นโหมดฝึก ไม่เปลี่ยนสถานะ “ฉันถึงแล้ว” ของทริปจริง</small>';timeline.parentNode.insertBefore(box,timeline)},100)}
function css(){var doc;try{doc=frame.contentDocument}catch(e){return}if(!doc||doc.getElementById('jc-simulator-fix-style'))return;var x=doc.createElement('style');x.id='jc-simulator-fix-style';x.textContent='.jc-simulator-card{padding:13px;margin:10px 0 14px;border:2px dashed #8c4163;border-radius:17px;background:#fff8d8;color:#4d3040}.jc-simulator-card>div{padding:7px 0;border-bottom:1px solid #eadfb7}.jc-simulator-card small,.jc-simulator-card strong,.jc-simulator-card span{display:block}.jc-simulator-card small{font-size:10px;color:#795f65}.jc-simulator-card .current strong{font-size:17px;color:#ad315f}.jc-simulator-card .current span{font-size:20px;font-weight:900;margin-top:2px}';doc.head.appendChild(x)}
document.addEventListener('click',function(e){if(e.target.closest('[data-jc-sim-start]'))setTimeout(function(){var plan=document.querySelector('.nav [data-root="plan"]');if(plan)plan.click();setTimeout(function(){css();render()},150)},20);if(e.target.closest('[data-jc-sim-stop]'))setTimeout(function(){var doc;try{doc=frame.contentDocument}catch(x){return}var old=doc&&doc.querySelector('.jc-simulator-card');if(old)old.remove()},50)},true);
frame.addEventListener('load',function(){setTimeout(function(){css();render()},300)});
})();
